# Cluster configuration for SLURM
# Save as cluster_config.yaml

# Default cluster settings
__default__:
  partition: "compute"
  time: "02:00:00"
  mem: "8G"
  nodes: 1
  ntasks: 1
  cpus-per-task: 1
  output: "logs/slurm-%j.out"
  error: "logs/slurm-%j.err"

# Rule-specific settings
get_country_list:
  time: "00:30:00"
  mem: "4G"
  
process_country:
  time: "02:00:00"
  mem: "8G"
  
process_country_cluster:
  time: "02:00:00"
  mem: "8G"
  
combine_results:
  time: "01:00:00"
  mem: "16G"
